services:
  - type: pserv
    name: pdeditor-postgres
    plan: free
    region: frankfurt
    ipAllowList: []

  - type: web
    name: pdeditor-backend
    runtime: python
    plan: free
    region: frankfurt
    rootDir: backend
    buildCommand: pip install --no-build-isolation -r requirements.txt
    startCommand: python -m uvicorn app.main:app --host 0.0.0.0 --port 8000
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.8
      - key: DATABASE_URL
        fromDatabase:
          name: pdeditor-postgres
          property: connectionString

  - type: static_site
    name: pdeditor-frontend
    rootDir: frontend
    buildCommand: npm install && npm run build
    publishPath: out
    envVars:
      - key: NEXT_PUBLIC_GOOGLE_CLIENT_ID
        sync: false
