"""add bug_reports table

Revision ID: 01fd6e2d14bc
Revises: 7ffbd97b3386
Create Date: 2026-06-24 12:30:42.409821
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '01fd6e2d14bc'
down_revision: Union[str, None] = '7ffbd97b3386'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bug_reports',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('page_url', sa.String(length=500), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bug_reports_status'), 'bug_reports', ['status'], unique=False)
    op.create_index(op.f('ix_bug_reports_user_id'), 'bug_reports', ['user_id'], unique=False)
    op.add_column('users', sa.Column('is_admin', sa.Boolean(), nullable=False))
    op.add_column('users', sa.Column('license_tier', sa.String(length=20), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'license_tier')
    op.drop_column('users', 'is_admin')
    op.drop_index(op.f('ix_bug_reports_user_id'), table_name='bug_reports')
    op.drop_index(op.f('ix_bug_reports_status'), table_name='bug_reports')
    op.drop_table('bug_reports')
    # ### end Alembic commands ###
