"""add license_tier_source to user

Revision ID: 5b4200ca661f
Revises: 28643a7be8ae
Create Date: 2026-07-10 18:26:35.733874
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5b4200ca661f'
down_revision: Union[str, None] = '28643a7be8ae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('license_tier_source', sa.String(length=20), nullable=False, server_default='admin', comment='admin=assigned by superadmin, stripe=paid via Stripe, free=default'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'license_tier_source')
    # ### end Alembic commands ###
