"""add platform app_version os_info to bug_reports

Revision ID: 5eec22a141a3
Revises: 01fd6e2d14bc
Create Date: 2026-06-25 18:47:56.996563
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5eec22a141a3'
down_revision: Union[str, None] = '01fd6e2d14bc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bug_reports', sa.Column('platform', sa.String(length=100), nullable=True))
    op.add_column('bug_reports', sa.Column('app_version', sa.String(length=50), nullable=True))
    op.add_column('bug_reports', sa.Column('os_info', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bug_reports', 'os_info')
    op.drop_column('bug_reports', 'app_version')
    op.drop_column('bug_reports', 'platform')
    # ### end Alembic commands ###
