"""add license_tier to user and license_features table

Revision ID: 7ffbd97b3386
Revises: 5010129f2dca
Create Date: 2026-06-24 09:50:27.369227
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7ffbd97b3386'
down_revision: Union[str, None] = '5010129f2dca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('license_features',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tier', sa.String(length=20), nullable=False),
    sa.Column('feature_key', sa.String(length=100), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_license_features_tier'), 'license_features', ['tier'], unique=False)
    op.add_column('users', sa.Column('is_admin', sa.Boolean(), nullable=False))
    op.add_column('users', sa.Column('license_tier', sa.String(length=20), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'license_tier')
    op.drop_column('users', 'is_admin')
    op.drop_index(op.f('ix_license_features_tier'), table_name='license_features')
    op.drop_table('license_features')
    # ### end Alembic commands ###
