"""add_is_guest_to_user

Revision ID: b069b95ef6e9
Revises: 6cabacce3a30
Create Date: 2026-07-26 10:51:18.735101
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b069b95ef6e9'
down_revision: Union[str, None] = '6cabacce3a30'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_guest', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_guest')
    # ### end Alembic commands ###
